<?php

/**
 * Implements hook_theme().
 */
function facetapi_tabs_theme($existing, $type, $theme, $path) {
  return [
    'facetapi_tabs' => [
      'variables' => [
        'facet' => NULL,
        'items' => [],
        'title' => '',
        'list_type' => 'ul',
        'wrapper_attributes' => [],
        'attributes' => [],
        'empty' => NULL,
        'context' => [],
      ],
    ],
    'facetapi_result_item' => [
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
      ],
    ],
  ];
}

/**
 * @param array $variables
 */
function facetapi_tabs_preprocess_facetapi_tabs(array &$variables) {
  template_preprocess_item_list($variables);
}
